# Generated by Django 4.2.5 on 2023-10-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_text", models.CharField(max_length=200)),
                ("bug_type_text", models.CharField(max_length=200)),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("status_text", models.CharField(max_length=50)),
            ],
        ),
    ]
