# Generated by Django 4.2.5 on 2023-10-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bug", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="bug", table="bugs",),
    ]
