# Generated by Django 4.2.5 on 2023-10-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bug", "0002_alter_bug_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="bug", table=None,),
    ]
